#!/bin/bash

printf "%-10s %-10s %s\n" "USER" "STARTED" "COMMAND"

ps -eo user,lstart,cmd --no-headers | while read user weekday month day time year cmd
do
    # Extract HH:MM:SS from the time field
    # lstart gives something like: Fri Dec  6 06:49:55 2025
    started=$(echo $time)

    printf "%-10s %-10s %s\n" "$user" "$started" "$cmd"
done
