#!/usr/bin/env bash
# Script that displays "I am invincible!!!" when receiving a SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
        echo "To infinity and beyond"
        sleep 2
done
