#!/usr/bin/env bash
# Displaying "Best School" 10 times and saying "Hi" on the 9th time
count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]; then
        echo "Hi"
    fi
    count=$((count + 1))
done
